list/list/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from ajax_select import urls as ajax_select_urls


urlpatterns = [
    path('listin/', include('listin.urls')),
    path('admin/', admin.site.urls),
    re_path(r'^ajax_select/', include(ajax_select_urls)),
]

list/listin/urls.py
from django.urls import path, include

from . import views

app_name = 'listin'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:book_id>', views.book_detail, name='book_detail'),
    path('new_book/', views.new_book, name='new_book'),
    path('new_author/', views.new_author, name='new_author'),
    path('login/', views.login_user, name='login_user'),
    path('register/', views.register, name='register'),
    path('register_done/', views.register, name='register'),
    path('logout/', views.logout_user, name='logout_user'),
    path('my_posts/', views.my_posts, name='my_posts'),
    path('new_post/', views.new_post, name='new_post'),
    path('<int:post_id>/', views.post, name='post'),
    path('all_books/', views.all_books, name='all_books'),
    path('all_authors/', views.all_authors, name='all_authors'),
    path('search_book/', views.search_book, name='search_book'),
    path('search_author/', views.search_author, name='search_author')
]

list/listin/models.py
from django.db import models
from django.conf import settings
from django.db.models.deletion import SET_DEFAULT, SET_NULL
from django.utils import timezone
from django.contrib.auth.models import User

class Book(models.Model):
    name = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=SET_DEFAULT, default='')
    release_date = models.DateField(blank=True, null=True)
    genre = models.ManyToManyField("Genre", blank=True)
    language = models.CharField(max_length=200, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    

    def __str__(self):
        return self.name

class Author(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    date_of_birth = models.DateField(blank=True, null=True)
    date_of_death = models.DateField(blank=True, null=True)

    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)

class Genre(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=400)
    content = models.TextField()
    published_date = models.DateTimeField(default=timezone.now)
    invisible = models.BooleanField(default=True)
    book = models.ForeignKey('Book', on_delete=models.CASCADE, default='')
    def __str__(self):
        return self.title

list/listin/forms.py
from django import forms
from django.contrib.auth.models import User
from ajax_select.fields import AutoCompleteSelectField


from .models import Book, Author, Genre, Post

class BookForm(forms.ModelForm):

    class Meta:
        model = Book
        fields = ('name', 'author', 'release_date', 'language', 'genre', 'description')

class AuthorForm(forms.ModelForm):

    class Meta:
        model = Author
        fields = ('first_name', 'last_name', 'date_of_birth', 'date_of_death')

class GenreForm(forms.ModelForm):

    class Meta:
        model = Genre
        fields = ('name',)

class RegistrationForm(forms.ModelForm):

    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    confirm_password = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_confirm_password(self):
        cd = self.cleaned_data
        if cd['password'] != cd['confirm_password']:
            raise forms.ValidationError('Passwords don\'t match. Please check it')
        return cd['confirm_password']

class LoginForm(forms.Form):
    username = forms.CharField(label='Username')
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

class PostForm(forms.ModelForm):
    # book = forms.ModelChoiceField(queryset=Book.objects.all(), widget=forms.TextInput)
    class Meta:
        model = Post
        fields = ('title', 'book', 'content', 'invisible')

    book = AutoCompleteSelectField('books', required=True)

    def clean_book(self):
        cd = self.cleaned_data
        print(cd['book'])
        print(Book.objects.get(name=cd['book']))
        if not Book.objects.get(name=cd['book']):
            raise forms.ValidationError('This book does not exists. Please add it')
        return cd['book']

list/listin/views.py
from django.http import request
from django.http.response import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.db.models import Q

import pdb




from .models import Book, Post, Author
from .forms import AuthorForm, BookForm, RegistrationForm, LoginForm, PostForm

# Create your views here.


def index(request):
    posts = Post.objects.filter(invisible=False).order_by('published_date')
    context = {'posts': posts}
    return render(request, 'listin/index.html', context)

#Posts
def my_posts(request):
    posts = Post.objects.filter(author=request.user.id)
    return render(request, 'listin/my_posts.html', {'posts': posts})

def post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'listin/post.html', {'post': post})

    
def new_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        print('post request')
        # try:
        #     Book.objects.get(name=form['book'].value())
        # except (Book.DoesNotExist):
        #     # form = PostForm()
        #     return render(request, 'listin/new_post.html', {'form': form, 'error_message': "This book does not exist on our site. Please, add it"})
        if form.is_valid():
            print('form is valid')
            form.instance.author = request.user
            post = form.save(commit=False)
            post.save()
            return HttpResponseRedirect(reverse('listin:my_posts'))
        
    else:
        print('else')
        form = PostForm()
    return render(request, 'listin/new_post.html', {'form': form})


#Books
def all_books(request):
    books = Book.objects.order_by('author')
    context = {'books': books}
    return render(request, 'listin/all_books.html', context)

def book_detail(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    return render(request, 'listin/book_detail.html', {'book': book})


def new_book(request):
    if request.method == 'POST':
        form = BookForm(request.POST)
        if form.is_valid():
            book = form.save(commit=False)
            book.save()
            return HttpResponseRedirect(reverse('listin:index'))
    else:
        form = BookForm()
    return render(request, 'listin/new_book.html', {'form': form})


def search_book(request):
    books_list = Book.objects.filter(name__icontains=request.GET['book_name'])
    if books_list is not None:
        return render(request, 'listin/search_book.html', {'books_list': books_list})
    else:
        return render(request, 'listin/search_book.html')

#Authors

def all_authors(request):
    authors = Author.objects.all()
    return render(request, 'listin/all_authors.html', {'authors': authors})

def new_author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid:
            author = form.save(commit=False)
            author.save()
            return HttpResponseRedirect(reverse('listin:index'))
    else:
        form = AuthorForm()
    return render(request, 'listin/new_author.html', {'form': form})

def search_author(request):
    name_list = request.GET['author_name'].split()
    try:
        if len(name_list) == 1:
            name1 = name_list[0]
            authors_list = Author.objects.filter(Q(first_name__icontains=name1)|\
                Q(last_name__icontains=name1))
        else:
            name1, name2 = name_list[0], name_list[1]
        
            authors_list = Author.objects.filter(Q(first_name__icontains=name1, last_name__icontains=name2)|\
                Q(first_name__icontains=name2, last_name__icontains=name1))
        
        if authors_list is not None:
            return render(request, 'listin/search_author.html', {'authors_list': authors_list})
        else:
            return render(request, 'listin/search_author.html')
    except:
        return render(request, 'listin/search_author.html')


#Users
def login_user(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(reverse('listin:index'))
                else:
                    return HttpResponse('Account is disabled')
            else:
                return HttpResponse('No such account')
    else:
        form = LoginForm()
    return render(request, 'listin/login.html', {'form': form})
    
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('listin:index'))

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data['password'])
            new_user.save()
            return render(request, 'listin/register_done.html', {'new_user': new_user})
    else:
        form = RegistrationForm()
    return render(request, 'listin/register.html', {'form': form})

list/listin/templates/listin/all_authors.html
{% extends "listin/base.html" %} 

{% block content %} 
    <h2>Authors</h2>
    <form action="{% url 'listin:search_author' %}" method="get">
        <input name='author_name' type='text' placeholder="Search author...">
    </form>
    <br>
    <a href="{% url 'listin:new_author' %}" class="btn btn-info">+ New author</a>
    <br>
    <br>
    {% if authors %} 
        <ul class="list-group list-group-flush">
            {% for author in authors %} 
                <li class="list-group-item"><a href="#">{{author.first_name}} {{author.last_name}}</a> </li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

list/listin/templates/listin/all_books.html
{% extends "listin/base.html" %} 
{% block content %}
    <a href="{% url 'listin:new_book' %}" class="btn btn-info">+ New book</a>
    
    <br>
    <br>
    {% if books %} 
        <ul class="list-group list-group-flush">
            {% for book in books %} 
                <li class="list-group-item"><a href="{% url 'listin:book_detail' book.id %}">{{book.name}}</a> Author: {{book.author}}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

list/listin/templates/listin/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-md">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggler collapsed" data_toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false" aria-controls="bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="{% url 'listin:index' %}">Listin</a>
                        <div class="collapse navbar-collapse" id="#bs-example-navbar-collapse-1">Label</div>
                    </div> 
                    <div>
                        {% if request.user.is_authenticated %} 
                            {{ request.user.username}} | <a href="{% url 'listin:logout_user' %}">Logout</a>
                            | <a href="{% url 'listin:my_posts' %}">My posts</a>
                        {% else %} 
                            <a href="{% url 'listin:register' %}">Registration</a>|<a href="{% url 'listin:login_user' %}">Login</a>
                        {% endif %}
                    </div> 
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            |<li><a href="{% url 'listin:index' %}">Home </a></li>
                            |<li><a href="{% url 'listin:all_books' %}">All books </a></li>
                            |<li><a href="{% url 'listin:all_authors' %}">All authors</a></li>
                            
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        {% block content %} {% endblock %}
    </body>
</html>

list/listin/templates/listin/book_detail.html
{% extends "listin/base.html" %} 

{% block content %} 
    <h2>{{book.name}} </h2>
    <p>Author:<a href="#"> {{book.author}}</a></p>
    <p>Release date:<a href="#"> {{book.release_date}}</a></p>
    <p>Genre: {% for genre in book.genre.all %}<a href="#">{{genre}}</a> {% endfor %}</p>
    <p>Language: <a href="#"> {{book.language}} </a></p>
    <p>{{book.description}}</p>
{% endblock %}

list/listin/templates/listin/index.html
{% extends "listin/base.html" %} 
{% block content %}

    <br>
    {% if posts %} 
        <ul class="list-group list-group-flush">
            {% for post in posts %} 
                <li class="list-group-item"><a href="{% url 'listin:post' post.id %}">{{post.title}}</a> Author: {{post.author}}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

list/listin/templates/listin/login.html
{% extends "listin/base.html" %} 

{% block content %} 
<h2>Log in</h2>
<form method="POST" action="{% url 'listin:login_user' %}">
    {{ form.as_p }} 
    {%csrf_token%} 
    <p><input type="submit" value="Log in"  class="save btn btn-success"></p>
</form>
{% endblock %}

list/listin/templates/listin/my_posts.html
{% extends "listin/base.html" %} 
{% block content %}
    <a href="{% url 'listin:new_post' %}" class="btn btn-info">+ New post</a>
    
    <br>
    <br>
    {% if posts %} 
        <ul class="list-group list-group-flush">
            {% for post in posts %} 
                <li class="list-group-item"><a href="{% url 'listin:post' post.id %}">{{post.title}}</a> Author: {{post.author}}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

list/listin/templates/listin/new_author.html
{% extends 'listin/base.html' %} 

{% block content %} 
<h2>New author</h2>
<form method="POST" action="{% url 'listin:new_author' %}">
    {%csrf_token%} 
    <p>First name {{ form.first_name }} </p><br>
    <p>Last name {{ form.last_name }} </p><br>
    <p>Date of birth {{ form.date_of_birth }}</p><br>
    <p>Date of birth {{ form.date_of_death }} </p><br>
    <button type="submit" class="save btn btn-success">Save</button>
</form>
{% endblock %}

list/listin/templates/listin/new_book.html
{% extends 'listin/base.html' %} 

{% block content %} 
<h2>New book</h2>
<form method="POST" action="{% url 'listin:new_book' %}">
    {%csrf_token%} 
    <p>Name {{ form.name }}  </p><br>
    <p>Author {{ form.author }} <a href="{% url 'listin:new_author' %}"  target="_blank">+ author</a> </p><br>
    <p>Release date {{form.release_date}}</p> <br>
    <p>Language {{form.language}}</p> <br>
    <p>Genres {{form.genre}}</p>
    <p>Description </p>{{ form.description }} <br>
    <button type="submit" class="save btn btn-success">Save</button>
</form>
{% endblock %}

list/listin/templates/listin/post.html
{% extends "listin/base.html" %} 

{% block content %} 
    <h2>{{post.title}}</h2>
    <p>{{post.author}}</p>
    <br/>
    <h3>{{post.book.name}} - {{post.book.author}}</h3>
    <p>{{post.content}}</p>
{% endblock %}

list/listin/templates/listin/register.html
{% extends "listin/base.html" %} 

{% block title %}Register an account{% endblock %} 

{% block content %} 
    <h2>Register an account</h2>
    <p>Please, use this form below to register your account</p>
    <form method="POST" action="{% url 'listin:register' %}">
        {{ form.as_p }} 
        {%csrf_token%} 
        <p><input type="submit" value="Register account"  class="save btn btn-success"></p>
    </form>
{% endblock %}

list/listin/templates/listin/register_done.html
{% extends 'listin/base.html' %} 

{% block content %} 
<p>Hello, {{ new_user.username }}! You are registered now!</p>
<a href="{% url 'listin:index' %}">Home page</a>
{% endblock %}

list/listin/templates/listin/search_author.html
{% extends 'listin/base.html' %} 

{% block content %} 
<form action="{% url 'listin:search_author' %}" method="get">
    <input name='author_name' type='text' placeholder="Search author...">
</form>
<br>
<br>
{% if authors_list %} 
    <ul class="list-group list-group-flush">
        {% for author in authors_list %} 
            <li class="list-group-item"><a href="#">{{author.first_name}} {{author.last_name}}</a></li>
        {% endfor %}
    </ul>
{% else %} 
    <p>No author has been found</p>
{% endif %}
{% endblock %}

list/listin/templates/listin/search_book.html
{% extends "listin/base.html" %} 
{% block content %}
    <form action="{% url 'listin:search_book' %}" method="get">
        <input name='book_name' type='text' placeholder="Search book...">
    </form>
    <br>
    <br>
    {% if books_list %} 
        <ul class="list-group list-group-flush">
            {% for book in books_list %} 
                <li class="list-group-item"><a href="{% url 'listin:book_detail' book.id %}">{{book.name}}</a> Author: {{book.author}}</li>
            {% endfor %}
        </ul>
    {% else %} 
        <p>No book has been found</p>
    {% endif %}
{% endblock %}